_wandb:
    value:
        cli_version: 0.18.7
        m:
            - "1": test_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": test_hit_rate@20
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test_mces@1
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_hit_rate@1
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_hit_rate@5
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_hit_rate@5
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_hit_rate@20
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_mces@1
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_hit_rate@1
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test_hit_rate@5
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test_hit_rate@1
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_hit_rate@20
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_mces@1
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 9
                - 49
                - 53
                - 55
                - 77
                - 103
            "2":
                - 1
                - 5
                - 9
                - 49
                - 53
                - 55
                - 77
                - 103
            "3":
                - 2
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.11.10
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": darwin-arm64
at_ks:
    value:
        - 1
        - 5
        - 20
bootstrap_metrics:
    value: false
bottleneck_factor:
    value: 1
df_test_path:
    value: null
dropout_rate:
    value: 0.2
formula_embedding_dim:
    value: 0
hidden_channels:
    value: 2048
log_only_loss_at_stages:
    value: []
lr:
    value: 0.001
myopic_mces_kwargs:
    value: null
node_feature_dim:
    value: 1024
num_gcn_layers:
    value: 3
num_skipblocks:
    value: 3
out_channels:
    value: 2048
use_formula:
    value: false
weight_decay:
    value: 0.0001
