featurizer:
  features: ['spectrum_embedding']
  feature_attributes:
    spectrum_embedding:
      path_to_embeddings: '/scratch/project/open-26-5/jozefov_147/PhantoMS/data/MSn_DreaMS.h5'
      identifier_col: 'identifiers'
      embedding_cols: 'embeddings'
      embedding_dim: 1024

data:
  spectra_mgf: "/scratch/project/open-26-5/jozefov_147/PhantoMS/data/20241211_msn_library_pos_all_lib_MSn.mgf"
  candidates_json: "/scratch/project/open-26-5/jozefov_147/PhantoMS/data/MassSpecGymMSn_retrieval_candidates_formula.json"
  split_file: "/scratch/project/open-26-5/jozefov_147/PhantoMS/data/20241211_split.tsv"
  max_allowed_deviation: 0.005
  batch_size: 32
  num_workers: 15
  hierarchical_tree: false

model:
  hidden_channels: 2048
  fp_size: 2048
  node_feature_dim: 1024
  dropout_rate: 0.2
  bottleneck_factor: 1.0
  num_skipblocks: 4
  num_gcn_layers: 3
  use_formula: true
  formula_embedding_dim: 64

metrics:
  at_ks: [1, 5, 20]

optimizer:
  lr: 0.001
  weight_decay: 0.0001

trainer:
  accelerator: "ddp"                  # Distributed Data Parallel
  devices: 2                          # Number of GPUs per node
  num_nodes: 1                        # Number of nodes
  max_epochs: 30                      # Train for exactly 30 epochs
  log_every_n_steps: 50               # Logging frequency
  check_val_every_n_epoch: 3          # Validate every 3 epochs
  limit_train_batches: 1.0            # Use 100% of training data
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  checkpoint_monitor: "val_loss"      # Monitor validation loss
  save_top_k: 2                       # Save top 2 models
  checkpoint_mode: "min"              # Minimize validation loss
  checkpoint_dir: "checkpoints/"      # Directory to save checkpoints

experiment_base_name: "name"

wandb:
  project: "PhantoMS_Retrieval"
  entity: "jozefov-iocb-prague"