featurizer:
  features: ['collision_energy', 'ionmode', 'adduct', 'spectrum_stats', 'atom_counts', 'value', 'retention_time', 'ion_source', 'binned_peaks']
  feature_attributes:
    atom_counts:
      top_n_atoms: 12
      include_other: true

data:
  file_mgf: "/Users/macbook/CODE/Majer:MassSpecGym/data/MSn/20241211_msn_library_pos_all_lib_MSn.mgf"
  file_json: "/Users/macbook/CODE/Majer:MassSpecGym/data/Retrieval/MassSpecGym_retrieval_candidates_mass.json"
  split_file: "/Users/macbook/CODE/Majer:MassSpecGym/data/MSn/20241211_split.tsv"
  max_allowed_deviation: 0.005
  batch_size: 50
  num_workers: 0

model:
  hidden_channels: 128
  fp_size: 4096
  node_feature_dim: 1039

metrics:
  at_ks: [1, 5, 20]

optimizer:
  lr: 0.001
  weight_decay: 1e-4

trainer:
  accelerator: "cpu"  # Change to "gpu" if available
  devices: 1
  max_epochs: 7
  log_every_n_steps: 10
  limit_train_batches: 2
  limit_val_batches: 2
  limit_test_batches: 2
  checkpoint_monitor: "val_loss"
  save_top_k: 3
  checkpoint_mode: "min"
  checkpoint_dir: "checkpoints/"

logs:
  dir: "logs"
  name: "gnn_retrieval_model"