featurizer:
  features: ['binned_peaks']
  feature_attributes:
    binned_peaks:
      max_mz: 1000
      bin_width: 0.25
      to_rel_intensities: true

data:
  file_mgf: "/Users/macbook/CODE/Majer:MassSpecGym/data/MSn/min_sample_trees.mgf"
  file_json: "/Users/macbook/CODE/Majer:MassSpecGym/data/candidates_generation/MassSpecGymMSn_retrieval_candidates_formula.json"
  split_file: "/Users/macbook/CODE/Majer:MassSpecGym/data/MSn/20241211_split.tsv"
  max_allowed_deviation: 0.005
  batch_size: 2
  num_workers: 0

model:
  hidden_channels: 2048  # Updated to 2048 as per your suggestion
  fp_size: 2048
  node_feature_dim: 1039
  dropout_rate: 0.2
  bottleneck_factor: 1.0  # Prevent dimension reduction in SkipBlocks
  num_skipblocks: 3        # Number of SkipBlocks
  num_gcn_layers: 3        # Number of GCN layers
  use_formula: true       # New parameter to enable formula integration
  formula_embedding_dim: 64  # Dimensionality for formula encoding

metrics:
  at_ks: [1, 5, 20]

optimizer:
  lr: 0.001
  weight_decay: 0.0001

trainer:
  accelerator: "cpu"  # Change to "gpu" if available
  devices: 1
  max_epochs: 2
  log_every_n_steps: 10
  limit_train_batches: 2  # Increased to allow logging every 10 steps
  limit_val_batches: 2
  limit_test_batches: 2
  checkpoint_monitor: "val_loss"
  save_top_k: 3
  checkpoint_mode: "min"
  checkpoint_dir: "checkpoints/"

logs:
  dir: "logs"
  name: "gnn_retrieval_model_bonus"

experiment_base_name: "experiment"  # Base name for experiments

wandb:
  project: "PhantoMS_Retrieval"
  entity: "jozefov-iocb-prague"